version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

  crawler_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker -Q crawling -n crawler@%h --loglevel=INFO
    volumes:
      - ./:/app
    environment:
      - SELENIUM_HUB_URL=http://selenium-chrome:4444/wd/hub
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - minio
      - selenium-chrome

  processor_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker -Q processing -n processor@%h --loglevel=INFO
    volumes:
      - ./:/app
    environment:
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  storage_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker -Q storage -n storage@%h --loglevel=INFO
    volumes:
      - ./:/app
    environment:
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - minio

  media_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker -Q media -n media@%h --loglevel=INFO
    volumes:
      - ./:/app
    environment:
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - minio

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - crawler_worker
      - processor_worker
      - storage_worker
      - media_worker

volumes:
  minio_data: